---
apiVersion: v1
kind: Service
metadata:
  name: auto-tracing-mutating-webhook
  labels:
    app: auto-tracing-mutating-webhook
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 5000
  selector:
    app: auto-tracing-mutating-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-tracing-mutating-webhook
  labels:
    app: auto-tracing-mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-tracing-mutating-webhook
  template:
    metadata:
      name: auto-tracing-mutating-webhook
      labels:
        app: auto-tracing-mutating-webhook
    spec:
      containers:
        - name: auto-tracing-mutating-webhook
          image: k0diak/auto-tracing-webhook:latest
          imagePullPolicy: Always
          env:
          - name: JAEGER_AGENT_PORT
            value: "5775"
          - name: JAEGER_AGENT_HOST
            value: "jaeger-agent.default.svc"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: auto-tracing-mutating-webhook
  labels:
    app: auto-tracing-mutating-webhook
webhooks:
  - name: auto-tracing-mutating-webhook.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lVSHk4UE02YVlnVlJQTHhicmFKVDlZTE4zUVZnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0FEQWVGdzB5TURBMk1UY3hNek0wTVRKYUZ3MDBOekV4TURNeE16TTBNVEphTUFBd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFES2ZLckNFMmpvdHMvNk9zVlp6dmVMcExSUjJWbkNlNDNoCktIN29ydTBENStmY2E5alp0d1lnNk96RTJnNzVFdmNGYmpBdHpXc1lpTHZ6UXBCMkNlbi9EY2RPdnVGU3hxVWwKL2UzSlU2LzdlQkFLclhYRis0TUcxamRnQXk1dEt2QWt3a1crV1J5YWlISjZ6V1NCOXlTOWloS0IzNi9HamF5NQoxeWZhenhBdjNYc3Z1c25ZRDJET2UvaWtsa1Vjc0hiWmpjSE9hN1gvWFNjY0JCLzJYSTRvWDJBYjFtMDc0ajdmCnVza01Sb1hMbFUyZWwrdEtCK2Q5cVRSV0dsY3RMc0g0aGFZVWtyUEtuZU9pNExjdHBaK1JTSTV6UGVNempMeEEKR3RWRUNlQTVoS0RtNjBaZkIxaE45TEQ0dVlRMHIwWnM3cXU3OFBxOUlZZ1pUbVZvM0t3TEFnTUJBQUdqVXpCUgpNQjBHQTFVZERnUVdCQlRVM1E0Tkk5QjZRNnFGaXdYU1I0d1diNzVxY3pBZkJnTlZIU01FR0RBV2dCVFUzUTROCkk5QjZRNnFGaXdYU1I0d1diNzVxY3pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQkhGTmFWMDZkd0JmWmd6NitJVzVYeEoxV2N1b3ZMZlYyWWY4V1N0TVRkYkF1RjdCQjV0Qkh2aTFuOQpLd0VKZWdFd2lubllHUUNRWjdOcW0vRVZ4cUdzaURNeGVEanc5dFkyWnpIaXg4dEtNd3IrYnBoaXUvTDlRanRnCi9PSFJJZEdaWCs2V3Bqa0lJYUozYk5rb1NNOG1mL1QvWXVIK25rbndTcWtuaXBDZE8rZlA2anJ0WG1mdnRNelIKdTg0OGZyWGxtcjhLeEJIRjkxckNuZlQraWlhOE44OE54Rmc4NEhUbEpuUkoyTWRnOUd6LzFXOXMwYWpRVlVDaApqbjdBalBhMHdXcjNRNTFESnppN2FDL1FZTFhNTnp3N0xZanRPWTdacGlKZkdYMEwyckFTcURjWUpobDhxM0NLClBQWjZWbVBzeGFaMXZZb0paRUZGQkwzNjZTWU0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: auto-tracing-mutating-webhook
        namespace: default
        path: "/decorate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        autotrace: enabled
